### ISSUE TITLE
Stucking after acquisition

### ISSUE THREAD

**Issue by Fabiobsc110** [prosch88/UFADE#6] opened 2024-10-10 12:48 UTC
HI
I have a problem in the GUI version of UFADE for windows. It recognizes the phone without problems, acquires the device, but does not finalize the task. Once it reaches 100% it does not proceed with the operations. The application responds but it is as if it is unable to close the generated tar (in the destination folder I correctly see the tar_temp folder).
Any ideas?
Thanks

**Comment by prosch88** [comment] 2024-10-10 13:42
Also:
- What type of Phone?
- What type of acquisition?

**Comment by Fabiobsc110** [comment] 2024-10-10 13:53
Thanks for the reply.
I used the compiled version.
the terminal doesn't appear when I run the exe.
Is there a way to recall it?

iPhone XR
Logical + Backup

**Comment by prosch88** [comment] 2024-10-10 13:57
Just checked the Windows version but I can't reproduce the issue. Make sure to use a reliable cable connection. If you clone the repository, you can run UFADE from the terminal and get an error output.

**Comment by jensstigaard** [comment] 2024-10-15 11:03
I have experienced the same issue as described by the original author.
I use the Win executable version 0.9.4.
I am attempting to acquire a Apple iPhone 12 running iOS 18.0.1.
UFED style Logical acquisition.
The phase that the application is stuck in during acquisition, is in "Performing Extraction of Shared App-Files".
The application shows the process is 100%, but never proceeds from there.
As far as I can see, the issue is possibly related to the method `shared_app_files` (https://github.com/prosch88/UFADE/blob/main/ufade_gui.py#L1351)
As I see in the .tar_tmp dir, some directories are created, and I am not sure whether files are actually put here during acquisition for further processing.

Perhaps the logging should be extended somehow, for actually giving some feedback on how much is processed.

**Comment by prosch88** [comment] 2024-10-15 12:08
Does the issue occur with the "regular" advanced extraction too?

**Comment by DRCRecoveryData** [comment] 2024-10-29 06:29
Tested on Iphone 11 Pro IOS 18.0.1:

- [x] Sreenshoot working
- [x] UFED style Logical acquisition working
- [ ] Storage status bar not show %
<img width="247" alt="2024-10-29_132742" src="https://github.com/user-attachments/assets/87c8255d-652e-45a1-980e-35491fd29ab3">

**Comment by prosch88** [comment] 2024-10-29 06:32
What's the output for Capacity and Used?

**Comment by DRCRecoveryData** [comment] 2024-10-29 06:35
Disk Use:    	▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
Capacity:    	64.00 GB
Used:        	62.39 GB
Free:        	1.61 GB

Ah i mean the bar look like not have % and Capacity and Used still show normal

**Comment by prosch88** [comment] 2024-10-29 06:38
Your disk is almost full (at least pmd3 is reporting this). The output is correct. The disk usage output in the device menu may differ.

**Comment by DRCRecoveryData** [comment] 2024-10-29 06:40
> Your disk is almost full (at least pmd3 is reporting this). The output is correct. The disk usage output in the device menu may differ.

Does the gui can be full screen when click maximum button?

I have an checkm8 ramdisk files list to boot into ramdisk and extract via ssh can you add to full filesystem part?

**Comment by prosch88** [comment] 2024-10-29 06:52
Scaling to fullscreen isn't activated. You may change this if you want: "self.resizable(False, False) to (True, True)" But this will mess with the button layout and most likely break some functions.

So how big is your ramdisk collection? Adding this to the repo would make the tool incredibly big. A submodule may be possible. It's possible to add this but not easily done for all supported platforms. You need a way to enter pwndfu. Ipwndfu could be added for linux and macos. On Windows libusbk could be used. Also ipwndfu does not work reliable for all checkm8 devices. I prefer to implement functions that work kind of reliable on all platforms.
There is a lot that can go wrong, you see? ;)

**Comment by DRCRecoveryData** [comment] 2024-10-29 06:53
> Scaling to fullscreen isn't activated. You may change this if you want: "self.resizable(False, False) to (True, True)" But this will mess with the button layout and most likely break some functions.
> 
> So how big is your ramdisk collection? Adding this to the repo would make the tool incredibly big. A submodule may be possible. It's possible to add this but not easily done for all supported platforms. You need a way to enter pwndfu. Ipwndfu could be added for linux and macos. On Windows libusbk could be used. Also ipwndfu does not work reliable for all checkm8 devices. I prefer to implement functions that work kind of reliable on all platforms. There is a lot that can go wrong, you see? ;)

yes, how can i contact you before release them ? ^^

**Comment by DRCRecoveryData** [comment] 2024-10-29 07:12
After fixing size by:
```
class MyApp(ctk.CTk):
    def __init__(self):
        super().__init__()

        self.stop_event = threading.Event()

        # Define Window to Maximize
        self.title("Universal Forensic Apple Device Extractor 0.9.4")
        self.state('zoomed')  # Maximizes the window on Windows
        self.resizable(True, True)

        if platform.uname().system == "Darwin":
            self.iconpath = ImageTk.PhotoImage(file=os.path.join(os.path.dirname(__file__), "assets", "ufade.icns"))
        else:
            self.iconpath = ImageTk.PhotoImage(file=os.path.join(os.path.dirname(__file__), "assets", "ufade.png"))
        self.wm_iconbitmap()
        self.iconphoto(False, self.iconpath)

        # Font
        self.stfont = ctk.CTkFont("default")
        self.stfont.configure(size=14)

        # Create Frames with grid configuration to make them responsive
        self.left_frame = ctk.CTkFrame(self, width=340, corner_radius=0, fg_color="#2c353e", bg_color="#2c353e")
        self.left_frame.grid(row=0, column=0, sticky="nswe")
        self.grid_columnconfigure(0, weight=1)
        self.grid_rowconfigure(0, weight=1)

        self.right_frame = ctk.CTkFrame(self, fg_color="#212121")
        self.right_frame.grid(row=0, column=1, sticky="nswe")
        self.grid_columnconfigure(1, weight=3)

        # Widgets (left Frame)
        if platform.uname().system == 'Windows':
            self.info_text = ctk.CTkTextbox(self.left_frame, fg_color="#2c353e", corner_radius=0, font=("Consolas", 14), activate_scrollbars=False)
        elif platform.uname().system == 'Darwin':
            self.info_text = ctk.CTkTextbox(self.left_frame, fg_color="#2c353e", corner_radius=0, font=("Menlo", 14), activate_scrollbars=False)
        else:
            self.info_text = ctk.CTkTextbox(self.left_frame, fg_color="#2c353e", corner_radius=0, font=("monospace", 14), activate_scrollbars=False)
        if lockdown is not None:
            self.info_text.configure(text_color="#abb3bd")
        else:
            self.info_text.configure(text_color="#4d5760")
        self.info_text.insert("0.0", device)
        self.info_text.configure(state="disabled")
        self.info_text.pack(fill="both", expand=True, padx=10, pady=10)

        # Initialize menu
        self.menu_var = StringVar(value="MainMenu")

        # Placeholder for dynamic frame
        self.dynamic_frame = ctk.CTkFrame(self.right_frame, corner_radius=0, bg_color="#212121")
        self.dynamic_frame.pack(fill="both", expand=True, padx=0, pady=0)
        self.current_menu = None

        # Show Main Menu
        if lockdown is not None:
            if ispaired:
                self.show_cwd()
            else:
                self.show_notpaired()
        else:
            self.show_nodevice()
```
<img width="960" alt="2024-10-29_141122" src="https://github.com/user-attachments/assets/030a0d27-a467-4b12-9a2f-cfcb545a22e7">
<img width="960" alt="2024-10-29_141152" src="https://github.com/user-attachments/assets/c890b89b-80e0-4288-be19-87fe40a12d01">

**Comment by prosch88** [comment] 2024-10-29 07:15
Use it this way if you like. I'm keeping the size as it is.

**Comment by DRCRecoveryData** [comment] 2024-10-31 01:39
> Use it this way if you like. I'm keeping the size as it is.

I have test that screenshoot is stuck when taking some screenshoot in roll page up in Messenger app can you check this issue on ios 17 and ios 18?

**Comment by prosch88** [comment] 2024-10-31 06:50
Are you able to start the flow again after it got stuck? The flow is depending on the design of the app, the usage of gifs and so on.

**Comment by prosch88** [comment] 2024-12-31 12:20
As there is no further feedback on this I'm closing this issue. Most likely the problem comes from the Windows filename lenght limitation.

**Closed by prosch88** 2024-12-31 12:20 UTC
